### PR TITLE
Let's get this merge!

### PR DESCRIPTION
**Pull request by Erouan50**
Hi guys,

Thanks for initiating this useful ansible improvement; starting where you left, the new inventory implementation is now featured completely if I forgot nothing, let's get this merged!

### CODE REVIEW

**Review by seanmalloy — COMMENTED** [review]
I think this looks fine, but I'm not that familiar with this code. I'll have some other people review this before we merge it.

**Comment by seanmalloy** [comment]
@Erouan50 thanks for your contribution! Is your intent to get our new GCE inventory script merged into the upstream Ansible repo once we get your changes merged in here?

@maurofaccenda  and @zbikmarc could you please review when you get a chance?

**Comment by Erouan50** [comment]
@seanmalloy yes it would be great!

**Comment by zbikmarc** [comment]
Will it be able to consume `GOOGLE_APPLICATION_CREDENTIALS` environment variable or role assigned to google cloud instance? Because this is what `GoogleCredentials.get_application_default()` was doing.

**Comment by Erouan50** [comment]
Yes if none of "Ansible authentication" is used, the following ones are used in order of precedence:
* Environment variable GOOGLE_APPLICATION_CREDENTIALS pointing to a file with stored credentials information.
* Stored "well known" file associated with `gcloud` command line tool.
* Google App Engine (production and testing)
* Google Compute Engine production environment.

**Comment by zbikmarc** [comment]
Ok, I see this now in line 178.

**Review by maurofaccenda — APPROVED** [review]
lgtm

**Pull request merged**
